embed an icon to totem.exe

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -925,6 +925,8 @@ ac_ct_F77
 LIBTOOL
 GLIB_GENMARSHAL
 GLIB_MKENUMS
+HAVE_WINDRES_TRUE
+HAVE_WINDRES_FALSE
 TOTEM_VERSION_MAJOR
 TOTEM_VERSION_MINOR
 TOTEM_VERSION_MICRO
@@ -8055,7 +8057,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8058 "configure"' > conftest.$ac_ext
+  echo '#line 8060 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10166,11 +10168,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10169: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10171: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10173: \$? = $ac_status" >&5
+   echo "$as_me:10175: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10456,11 +10458,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10459: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10461: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10463: \$? = $ac_status" >&5
+   echo "$as_me:10465: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10560,11 +10562,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10563: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10565: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10567: \$? = $ac_status" >&5
+   echo "$as_me:10569: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12937,7 +12939,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12940 "configure"
+#line 12942 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13037,7 +13039,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13040 "configure"
+#line 13042 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15438,11 +15440,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15441: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15443: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15445: \$? = $ac_status" >&5
+   echo "$as_me:15447: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15542,11 +15544,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15545: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15547: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15549: \$? = $ac_status" >&5
+   echo "$as_me:15551: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17140,11 +17142,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17143: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17145: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17147: \$? = $ac_status" >&5
+   echo "$as_me:17149: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17244,11 +17246,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17247: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17249: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17251: \$? = $ac_status" >&5
+   echo "$as_me:17253: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19464,11 +19466,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19467: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19469: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19471: \$? = $ac_status" >&5
+   echo "$as_me:19473: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19754,11 +19756,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19757: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19759: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19761: \$? = $ac_status" >&5
+   echo "$as_me:19763: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19858,11 +19860,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19861: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19863: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19865: \$? = $ac_status" >&5
+   echo "$as_me:19867: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22750,6 +22752,18 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
+
+
+# check windres for embeding icons to windows executables
+
+
+if which windres > /dev/null; then
+  HAVE_WINDRES_TRUE=
+  HAVE_WINDRES_FALSE='#'
+else
+  HAVE_WINDRES_TRUE='#'
+  HAVE_WINDRES_FALSE=
+fi
 
 
 # Requirements
@@ -27092,6 +27106,13 @@ echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_WINDRES_TRUE}" && test -z "${HAVE_WINDRES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_WINDRES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_WINDRES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${TOTEM_GST_TRUE}" && test -z "${TOTEM_GST_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"TOTEM_GST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -27994,6 +28015,8 @@ ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
 GLIB_GENMARSHAL!$GLIB_GENMARSHAL$ac_delim
 GLIB_MKENUMS!$GLIB_MKENUMS$ac_delim
+HAVE_WINDRES_TRUE!$HAVE_WINDRES_TRUE$ac_delim
+HAVE_WINDRES_FALSE!$HAVE_WINDRES_FALSE$ac_delim
 TOTEM_VERSION_MAJOR!$TOTEM_VERSION_MAJOR$ac_delim
 TOTEM_VERSION_MINOR!$TOTEM_VERSION_MINOR$ac_delim
 TOTEM_VERSION_MICRO!$TOTEM_VERSION_MICRO$ac_delim
@@ -28030,8 +28053,6 @@ XVIDMODE_LIBS!$XVIDMODE_LIBS$ac_delim
 X_LIBS!$X_LIBS$ac_delim
 HAVE_XVIDMODE_TRUE!$HAVE_XVIDMODE_TRUE$ac_delim
 HAVE_XVIDMODE_FALSE!$HAVE_XVIDMODE_FALSE$ac_delim
-PYTHON!$PYTHON$ac_delim
-PYTHON_VERSION!$PYTHON_VERSION$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -28073,6 +28094,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PYTHON!$PYTHON$ac_delim
+PYTHON_VERSION!$PYTHON_VERSION$ac_delim
 PYTHON_PREFIX!$PYTHON_PREFIX$ac_delim
 PYTHON_EXEC_PREFIX!$PYTHON_EXEC_PREFIX$ac_delim
 PYTHON_PLATFORM!$PYTHON_PLATFORM$ac_delim
@@ -28162,7 +28185,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 87; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 89; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
